# L'env de travail
FROM python:3.12.2-slim


# le répertoire de travail
WORKDIR /app

# installer les dépendances
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copier le code
COPY . .

# Exposer le port 
EXPOSE 8501

# Commande pour démarrer Streamlit
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.headless=true"]