# L'env de travail
FROM python:3.12.2-slim


# le répertoire de travail
WORKDIR /app

# installer les dépendances
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copier le code 
COPY . .

# Exposer le port 
EXPOSE 8000

# Commande pour démarrer le backend
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
